---
# CentOS
# install requirements
- name: Requirement package
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - MySQL-python
    - epel-release
  notify:
    - Update server

#
#   NGINX
#

# install ngnix
- name: Install Nginx
  yum:
    name: nginx
    state: latest
  notify: 
    - Restart Nginx

# open port
- name: Open ports 80
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled

- name: Open ports 443
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled

# config nginx
- name: Config Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
    mode: 0644
  notify:
    - Reload firewalld
    - Restart Nginx
#
#   MARIADB 10.0
#

# add mariadb repo
- name: Add mariadb repo
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

# remove old mariadb package
- name: Remove old mariadb
  yum:
    name: mariadb*
    state: absent

# install mariadb
- name: Install MariaDB
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - MariaDB-server
    - MariaDB-client
  notify:
    - Restart MariaDB

# config mariadb
- name: Sets the root password 
  mysql_user: 
    login_user: root 
    login_password: "{{ mysql_root_password }}" 
    host: localhost 
    check_implicit_admin: yes
    name: root
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'


- name: Deletes anonymous MySQL server user for localhost
  mysql_user: 
    login_user: root 
    login_password: "{{ mysql_root_password }}" 
    host: localhost 
    check_implicit_admin: yes
    name: ""
    state: "absent"

- name: remove the MySQL test database
  action: mysql_db login_user=root login_password="{{ mysql_root_password }}" db=test state=absent


#
#    PHP
#

# add webtatic repo
- name: Add Webtatic repo fo PHP7
  yum:
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    state: present

# remove old version
- name: Remove old PHP
  yum:
    name: php*
    state: absent

# install php
- name: Install PHP-7.1
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - php71w
    - php71w-fpm
    - php71w-common

# config php
- name: Config PHP
  template: 
    src: php.ini.j2
    dest: /etc/php.ini
    mode: 0644
  notify:
    - Restart Nginx
    - Restart php-fpm
