---
# CentOS
# install requirements
- name: Requirement package
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - MySQL-python
    - epel-release
  notify:
    - Update server

#
#   NGINX
#

# install ngnix
- name: Install Nginx
  yum:
    name: nginx
    state: latest
  notify: 
    - Restart Nginx
  tags:
    - nginx

# open port 80
- name: Open ports 80
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled

# open port 443
- name: Open ports 443
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled

- name: Reload Firewalld
  shell: firewall-cmd --reload

# config nginx
- name: Config Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
    mode: 0644
  notify:
    - Reload firewalld
    - Restart Nginx
  tags:
    - nginx
#
#   MARIADB 10.0
#

# add mariadb repo
- name: Add mariadb repo
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
  tags:
    - mariadb

# remove old mariadb package
- name: Remove old mariadb
  yum:
    name: mariadb*
    state: absent
  tags:
    - mariadb

# install mariadb
- name: Install MariaDB
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - MariaDB-server
    - MariaDB-client
  tags:
    - mariadb

- name: Start MariaDB
  systemd:
    name: mariadb
    state: started
    enabled: yes

# config mariadb
- name: Sets the root password 
  mysql_user: 
    login_user: root 
    login_password: "{{ mysql_root_password }}" 
    host: localhost 
    check_implicit_admin: yes
    name: root
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
  tags:
    - mariadb

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: 
    login_user: root 
    login_password: "{{ mysql_root_password }}" 
    host: localhost 
    check_implicit_admin: yes
    name: ""
    state: "absent"
  tags:
    - mariadb

- name: remove the MySQL test database
  action: mysql_db login_user=root login_password="{{ mysql_root_password }}" db=test state=absent
  tags:
    - mariadb

#
#    PHP
#

# add webtatic repo
- name: Add Webtatic repo fo PHP7
  yum:
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    state: present
  tags:
    - php

# remove old version
- name: Remove old PHP
  yum:
    name: php*
    state: absent
  tags:
    - php

# install php
- name: Install PHP-7.1
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - php71w
    - php71w-fpm
    - php71w-common
  tags:
    - php

# config php
- name: Config PHP
  template: 
    src: php.ini.j2
    dest: /etc/php.ini
    mode: 0644
  notify:
    - Restart Nginx
    - Restart php-fpm
  tags:
    - php