---
# handlers file for lemp-stack
- name: Start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted

- name: Restart MariaDB
  systemd:
    name: mariadb
    state: restarted

- name: Update server
  yum:
    name: '*'
    state: latest

- name: Restart php-fpm
  systemd:
    name: php-fpm
    state: restarted

- name: Reload firewalld
  systemd:
    name: firewalld
    state: restart